```{r setup, include = FALSE}
rm(list = ls())
library(tidyverse)
library(haven)
```


```{r data, include = FALSE}
data_EGOV_ori <- read.csv("./data/EGOV_DATA.csv")
region_list   <- read.csv("./data/Country_list.csv")
data_PS       <- read_dta("./data/ps_data.dta")
data_VD       <- readRDS("./data/V-Dem-CY-Full+Others-v12.rds")

```


```{r regional_matching, include=FALSE}

## list for country name
region_list_sub1 <- region_list %>% 
                    select(name, region) %>% 
                    rename("Country" =  name)

## list for country ID 
region_list_sub2 <- region_list %>% 
                    select(name, alpha.3) %>% 
                    rename("Country" =  name) %>% 
                    rename("ID" =  alpha.3)

## merge with EGOV data
data_EGOV_temp <- data_EGOV_ori %>% 
                  mutate(Country = 
                           ifelse(str_sub(Country.Name, start = -1, end = -1) == " ", #delete the last white space
                                  str_sub(Country.Name, start =  1, end = -2),
                                          Country.Name)) %>% 
                  left_join(region_list_sub1, by = "Country")  

## Na cleaning
no_match_list  <- unique(data_EGOV_temp$Country.Name[is.na(data_EGOV_temp$region)]) # countries with no match


## no_match_list
no_match_table <- data.frame(Country = no_match_list,
                             region = c("Asia", "Europe", "Americas", "Africa", "Europe",
                                        "Asia", "Africa", "Asia", "Americas", "Africa"),
                             ID     = c("KOR", "MDA", "BOL", "CIV", "CZE",
                                        "PRK","COD", "GEO", "VEN", "TZA"))

## re-merge
data_EGOV <- data_EGOV_temp %>% 
             left_join(no_match_table, by = c("Country.Name" = "Country")) %>%  ## merge with EGOV data
             mutate(region = ifelse(is.na(region.x), region.y, region.x)) %>%   ## integrate region cols
             select(-c(region.x, region.y)) %>%                                 ## remove duplication
             left_join(region_list_sub2, by = "Country") %>%                    ## merge ID data
             mutate(ID = ifelse(is.na(ID.x), ID.y, ID.x)) %>%                   ## integrate ID cols
             select(-c(ID.x, ID.y))                                             ## remove duplication
             
          
#sum(is.na(data_EGOV$region)) #confirmation
```


```{r party strength, include= TRUE}
#gen v2psswitch_neg = -1 * v2psswitch
#egen v2psswitch_neg_std = std(v2psswitch_neg)
#egen v2pscohesv_std = std(v2pscohesv)
#gen v2pscnslnl_neg = -1 * v2pscnslnl
#egen v2pscnslnl_neg_std = std(v2pscnslnl_neg)
#egen v2psprlnks_std = std(v2psprlnks)
#egen v2psorgs_std = std(v2psorgs)
#egen v2psprbrch_std = std(v2psprbrch)
#gen ps = (v2pscohesv_std + v2psswitch_neg_std + v2pscnslnl_neg_std + v2psprlnks_std + v2psorgs_std + #v2psprbrch_std)/6 

# create party strength index
data_VD_2000 <-data_VD %>% 
               filter(year > 1999) %>%  ## standardize after 2000 (arbitrary choice)
               mutate(v2pscohesv_std     = (   v2pscohesv - mean(v2pscohesv))   /sd(   v2pscohesv),
                      v2pscnslnl_neg_std = (-1*v2pscnslnl - mean(-1*v2pscnslnl))/sd(-1*v2pscnslnl),
                      v2psprlnks_std     = (   v2psprlnks - mean(v2psprlnks))   /sd(   v2psprlnks),
                      v2psorgs_std       = (   v2psorgs   - mean(v2psorgs))     /sd(   v2psorgs  ),
                      v2psprbrch_std     = (   v2psprbrch - mean(v2psprbrch))   /sd(   v2psprbrch),
                      ps_2020 = (v2pscohesv_std + v2pscnslnl_neg_std + v2psprlnks_std 
                                 + v2psorgs_std + v2psprbrch_std)/5) %>% 
               left_join(select(data_PS, c("country_text_id", "year", "ps")), by = c("country_text_id", "year"))

## comparison with original party strength index
data_VD_2000 %>% 
        ggplot(aes(x = ps_2020, y = ps))+
        geom_point()+
        labs(title   = "The Comparison of Party Strength Index after 1999",
             x       = "Original Party Strength Index with 6 variables",
             y       = "New Party Strength Index with 5 variables",
             caption = "New Party strength Index is derived from data after 1999.")

ggsave("./output/Fig_01_EGOV_Comp.jpeg")

```


```{r regime, include=TRUE}
## For Younmi chart
## regime classification data (given country ID)
regime <- c("LD","ED","ED+","LD","LD","LD-","LD-","LD-","LD","LD",
            "LD","LD","ED","ED","LD-","ED","LD-","LD","LD","LD-",
            "ED+","LD","ED+","ED","ED+","ED+","EA+")


data_VD_EU_2020 <- data_VD_2000 %>% 
                   filter(year == 2020,
                          country_id %in% c(144, 148, 152, 156,157,77,158,161,164, 96,
                          163,76,154,210,81,82,173,174,84,178,91,
                          17,21,190,5,202,201)) %>% 
                   select(country_name, ps_2020) %>% 
                   mutate(regime = regime)

#write.csv(data_VD_EU_2020, "./data/data_VD_EU_2020.csv")


```



```{r data_combine, include= TRUE}

# important variable choices
VD_vars <- c("v2x_polyarchy", "v2x_libdem","v2x_accountability", "v2x_ex_confidence", "v2x_ex_direlect",
             "v2x_ex_hereditary", "v2x_ex_military", "v2x_ex_party", "v2x_neopat", "v2xnp_client", "v2xnp_pres",
             "v2xnp_regcorr", "v2x_civlib", "v2x_clphy", "v2x_clpol", "v2x_clpriv", "v2xpe_exlecon", "v2xpe_exlgeo",
             "v2xpe_exlpol", "v2xpe_exlsocgr", "v2x_corr", "v2x_execorr", "v2x_pubcorr",
             "v2x_rule", "v2xdd_i_ci", "v2xdd_i_rf", "v2xdd_i_or", "v2xdd_i_pl", "v2xdd_cic",
             "v2xdd_toc", "v2xcs_ccsi", "v2x_elecreg", "v2xex_elecreg", "v2xlg_elecreg", "v2x_EDcomp_thick",
             "v2x_freexp", "v2x_hosabort", "v2x_legabort", "v2xcl_disc", "v2xcl_dmove", "v2xel_elecparl",
             "v2xel_elecpres", "v2xex_elecleg", "v2xlg_leginter", "v2xme_altinf", "v2xps_party",
             "v2x_divparctrl", "v2x_feduni", "v2x_egaldem", "v2xel_frefair", "v2xcl_rol", 
             "v2x_jucon", "v2xlg_legcon", "v2elembaut", "v2elfrfair",
             "v2expathhs", "v2mecenefi", "v2cafres")


# data merged to EGOV (non continuous years...)
data_merged <-data_EGOV %>% 
              left_join(data_VD_2000, by = c("Survey.Year" = "year", "ID" = "country_text_id")) %>% 
              relocate(Survey.Year, Country.Name, region, ID) %>%    ## sort variables
              rename("year"   = Survey.Year,
                     "Region" = region)                           ## rename variables

# sort variables
temp_varlist <- colnames(data_merged)
temp_varlist[11:31] # unnecessary variables

data <- data_merged %>% 
        select(-temp_varlist[11:31])  ## remove unnecessary variables

write.csv(data, "./data/data.csv")
```


